GET http://localhost:8000/products/ HTTP/1.1

###

POST http://localhost:8000/products/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzg0NzM2Nzc1LCJpYXQiOjE3ODQ3MzMxNzUsImp0aSI6IjliNDJhOGRjYzhlMzRjYjhiZWE3YmUzNDQyMmRmMTE5IiwidXNlcl9pZCI6IjEifQ._rLUkp0oXenUbh2O3XMQmiuxkzgX4z-UBwoDydVWyQs

{
	"name": "Television",
	"price": 300.00,
	"stock": 11,
	"description": "An amazing new TV"    
}

###
POST http://127.0.0.1:8000/api/token/ HTTP/1.1
Content-Type: application/json

{
	"username": "ali",
    "password": "test"
}
### 
POST http://localhost:8000/api/token/ HTTP/1.1
Content-Type: application/json

{
	"username": "admin",
	"password": "test"
}

###
POST http://localhost:8000/api/token/ HTTP/1.1
Content-Type: application/json

{
	"username": "ahmed",
	"password": "test"
}

###
GET http://localhost:8000/products/ HTTP/1.1
Authorization: Bearer  eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzg0NzM2Nzc1LCJpYXQiOjE3ODQ3MzMxNzUsImp0aSI6IjliNDJhOGRjYzhlMzRjYjhiZWE3YmUzNDQyMmRmMTE5IiwidXNlcl9pZCI6IjEifQ._rLUkp0oXenUbh2O3XMQmiuxkzgX4z-UBwoDydVWyQs
###
POST http://localhost:8000/api/token/refresh/ HTTP/1.1
Content-Type: application/json

{
	"refresh" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc4NDAwNDgwMCwiaWF0IjoxNzgzOTE4NDAwLCJqdGkiOiIxZGNhMjk5OWZjZmU0YjE2OGFiOWMxZmNhN2U3OWI1ZSIsInVzZXJfaWQiOiIxIn0.ojIuHQE56M5_NtmZC8kUATcX4qtMNAtLd5j3rPy4VYE"
}

###
DELETE  http://localhost:8000/products/8/ HTTP/1.1


###
PATCH  http://localhost:8000/products/7/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzg0NzMyOTUzLCJpYXQiOjE3ODQ3MjkzNTMsImp0aSI6IjViM2E5YmZiZWJlNDQ4ZTRhYzY0NmNiNTBjMWFjY2I1IiwidXNlcl9pZCI6IjEifQ.sQiAYDWBn_buvLmtzhQ-BXOjAkYJVgVUlC3KvR0k7G4

{
	"stock": "8"
}

###
POST http://localhost:8000/orders/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzg0NzI4Njk0LCJpYXQiOjE3ODQ3MjgzOTQsImp0aSI6ImY0OGEyYzQxMDJhMDQxZmQ5OTA1MzZjMTNmZmRlYzQwIiwidXNlcl9pZCI6IjEifQ.4lrFeUzTpMECqrtA1NujHPk9dr0AJ2-y1u3R2awgz-0

{
   "order_status": "Pending",
    "items": [
      {
		"product" : 3,
        "quantity": 2
      },
      {
        "product" : 1,
        "quantity": 3
       
      }
    ] 
}